name: Build & Deploy Quarto (gh-page)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # Install R
      - uses: r-lib/actions/setup-r@v2

      # (Optional but helpful) Install R deps Quarto needs to knit
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # add whatever your .qmds need, e.g. any::knitr, any::rmarkdown, any::tidyverse, any::sf
          extra-packages: any::knitr, any::rmarkdown

      # Sanity check
      - name: Show versions
        run: |
          Rscript --version
          quarto --version

      # Render the site (writes to docs/ per your _quarto.yml)
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .

      # Deploy docs/ to gh-page
      - name: Deploy to gh-page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-page
          allow_empty_commit: true
